version: "3.7"
services:
  node:
    container_name: app_node
    build: ./node
    volumes:
      - "./node:/home/node/app"
    ports:
      - 8080:8080
    restart: always
    tty: true
    networks:
      - app_net
  tor:
    container_name: app_tor
    image: peterdavehello/tor-socks-proxy:latest
    volumes:
      - ./torrc:/etc/tor/torrc
    ports:
      - 9050:9050
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.10

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
